name: stroll_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_gen: ^5.10.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  intl: any

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/proximanova_regular.ttf
        - asset: assets/fonts/proximanova_light.otf
          weight: 300
        - asset: assets/fonts/proximanova_bold.otf
          weight: 700
        - asset: assets/fonts/proximanova_black.otf
          weight: 900
        - asset: assets/fonts/proximanova_black.ttf
          weight: 900
        - asset: assets/fonts/proximanova_blackit.otf
          weight: 900
          style: italic
        - asset: assets/fonts/proximanova_boldit.otf
          weight: 700
          style: italic
        - asset: assets/fonts/proximanova_extrabold.otf
          weight: 800
